//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> prcatId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string CatgoryName { get; set; }
        public string Images { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
